/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package agh.toik.api;

import agh.toik.model.Difficulty;
import agh.toik.model.Question;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-19T18:19:31.581Z[GMT]")
@Api(value = "quiz", description = "the quiz API")
public interface QuizApi {

    @ApiOperation(value = "Finds quiz questions by query", nickname = "getQuizQuestions", notes = "Multiple parameters can be provided", response = Question.class, responseContainer = "List", tags={ "quiz", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Question.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid parameters") })
    @RequestMapping(value = "/quiz",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Question>> getQuizQuestions(@ApiParam(value = "How much Questions do you want", defaultValue = "5") @Valid @RequestParam(value = "quantity", required = false, defaultValue="5") Integer quantity
,@ApiParam(value = "How difficult Questions should be") @Valid @RequestParam(value = "difficulty", required = false) String difficulty
,@ApiParam(value = "Question category") @Valid @RequestParam(value = "category", required = false) String category
);

}
